<a href="https://colab.research.google.com/github/ROCKY-MAGIC/Ml/blob/main/DEEPLEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

1

In [4]:
t2 = torch.tensor([[4.,4,5,3],[6,4,3,2]])
t2
t2.shape

torch.Size([2, 4])

In [5]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b= torch.tensor(5.,requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [6]:
y = x * w + b
y

tensor(17., grad_fn=<AddBackward0>)

In [7]:
y.dtype

torch.float32

In [8]:
y.backward()

In [9]:
print(x.grad,w.grad,b.grad)

None tensor(3.) tensor(1.)


In [10]:
t2

tensor([[4., 4., 5., 3.],
        [6., 4., 3., 2.]])

In [11]:
t3 = torch.full((2,4), 3.)
t3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [12]:
t4 = torch.cat((t2,t3))

In [13]:
torch.sin(t4)

tensor([[-0.7568, -0.7568, -0.9589,  0.1411],
        [-0.2794, -0.7568,  0.1411,  0.9093],
        [ 0.1411,  0.1411,  0.1411,  0.1411],
        [ 0.1411,  0.1411,  0.1411,  0.1411]])

In [14]:
print(t4)
t4.reshape(8,2)

tensor([[4., 4., 5., 3.],
        [6., 4., 3., 2.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[4., 4.],
        [5., 3.],
        [6., 4.],
        [3., 2.],
        [3., 3.],
        [3., 3.],
        [3., 3.],
        [3., 3.]])

In [15]:
import numpy as np

x = np.array([[4.,5.],
             [4.,3.]])
x

array([[4., 5.],
       [4., 3.]])

In [16]:
y = torch.from_numpy(x)
y

tensor([[4., 5.],
        [4., 3.]], dtype=torch.float64)

In [17]:
x.dtype,y.dtype

(dtype('float64'), torch.float64)

In [18]:
z = y.numpy()
z


array([[4., 5.],
       [4., 3.]])

In [19]:
inputs = np.array([[73,67,43],
                    [91,88,64],
                    [87,134,58],
                    [103,43,37],
                    [69,96,70]],dtype = "float32")
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [103.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [20]:
targets = np.array([[56,70],
                    [81,101],
                    [119,133],
                    [22,37],
                    [103,119]], dtype = "float32")
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [21]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [103.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [22]:
w = torch.randn(2,3, requires_grad = True)
b = torch.randn(2, requires_grad = True)
w,b

(tensor([[ 1.0072, -1.0286, -0.1024],
         [ 0.3546, -0.0826, -0.4756]], requires_grad=True),
 tensor([-0.1897, -1.4913], requires_grad=True))

In [23]:
def model(x):
  return x @ w.t() + b

In [24]:
def mse(t1,t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [25]:
pred = model(inputs)
pred,targets

(tensor([[ 1.3553e-02, -1.5895e+00],
         [-5.6091e+00, -6.9285e+00],
         [-5.6340e+01, -9.2913e+00],
         [ 5.5531e+01,  1.3883e+01],
         [-3.6611e+01, -1.8243e+01]], grad_fn=<AddBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [26]:
def train(epochs):
  for epoch in range(epochs):
    preds = model(inputs)
    loss = mse(preds,targets)
    loss.backward()
    global w,b
    with torch.no_grad() :
      w -= w.grad * 1e-5
      b -= b.grad * 1e-5
      w.grad.zero_()
      b.grad.zero_()

In [27]:
train(856)
preds = model(inputs)
targets,preds,mse(preds,targets)

(tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]),
 tensor([[ 57.4162,  70.5290],
         [ 81.3138,  97.5530],
         [120.6003, 139.8215],
         [ 22.0484,  39.1289],
         [ 99.5368, 112.0736]], grad_fn=<AddBackward0>),
 tensor(12.7864, grad_fn=<DivBackward0>))

In [28]:
import torch.nn as nn

In [29]:

targets = torch.tensor([[56., 70],
[81, 101],

[119, 133],

[22, 37],

[103, 119],

[57, 69],

[80, 102],

[118, 132], [21, 38],

[104, 118],

[57, 69],

[82, 100],

[118, 134],

[20, 38],

[102, 120]])
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [30]:
inputs = torch.tensor([[73., 67, 43],

[91, 88, 64],

[87, 134, 58],

[102, 43, 37],

[69, 96, 70],

[74, 66, 43],

[91, 87, 65],

[88, 134, 59],

[101, 44, 37],

[68, 96, 71],

[73, 66, 44],

[92, 87, 64],

[87, 135, 57],

[103, 43, 36],

[68, 97, 70]])
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [31]:
from torch.utils.data import TensorDataset

In [32]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [33]:
from torch.utils.data import DataLoader

In [34]:
batch = 5
train_dl = DataLoader(train_ds,batch,shuffle=True)

In [35]:
for input,target in train_dl:
  print(input,target)

tensor([[102.,  43.,  37.],
        [ 88., 134.,  59.],
        [ 91.,  87.,  65.],
        [ 68.,  96.,  71.],
        [ 68.,  97.,  70.]]) tensor([[ 22.,  37.],
        [118., 132.],
        [ 80., 102.],
        [104., 118.],
        [102., 120.]])
tensor([[ 73.,  66.,  44.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 92.,  87.,  64.],
        [ 87., 134.,  58.]]) tensor([[ 57.,  69.],
        [ 56.,  70.],
        [ 81., 101.],
        [ 82., 100.],
        [119., 133.]])
tensor([[101.,  44.,  37.],
        [ 74.,  66.,  43.],
        [ 87., 135.,  57.],
        [ 69.,  96.,  70.],
        [103.,  43.,  36.]]) tensor([[ 21.,  38.],
        [ 57.,  69.],
        [118., 134.],
        [103., 119.],
        [ 20.,  38.]])


In [36]:
model = nn.Linear(3,2)
list(model.parameters())

[Parameter containing:
 tensor([[-0.1067, -0.4106,  0.2707],
         [-0.3736, -0.2558,  0.4831]], requires_grad=True),
 Parameter containing:
 tensor([0.2615, 0.0879], requires_grad=True)]

In [37]:
preds = model(inputs)
preds,targets

(tensor([[-23.3967, -23.5449],
         [-28.2544, -25.4946],
         [-48.3383, -38.6643],
         [-18.2628, -31.1393],
         [-27.5663, -16.4230],
         [-23.0929, -23.6628],
         [-27.5731, -24.7557],
         [-48.1743, -38.5547],
         [-18.5667, -31.0215],
         [-27.1888, -15.5663],
         [-22.7154, -22.8060],
         [-27.9505, -25.6124],
         [-49.0196, -39.4032],
         [-18.6403, -31.9961],
         [-27.8701, -16.3052]], grad_fn=<AddmmBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [38]:
import torch.nn.functional as f

In [39]:
loss_fn = f.mse_loss

In [40]:
loss = loss_fn(preds,targets)

In [41]:
loss


tensor(14176.3066, grad_fn=<MseLossBackward0>)

In [42]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [43]:
def fit(nu_epoch, model, loss_fn, opt, train_dl):
  for epoch in range(nu_epoch):
    for input,target in train_dl:
      pred = model(input)
      loss = loss_fn(pred,target)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1) % 10 == 0:
        print(f"Epoch [{epoch+1}/{nu_epoch}] : Loss = {loss.item()}]")

In [44]:
#fit(1000,model,loss_fn,opt,train_dl)

In [45]:
preds = model(inputs)
preds , targets

(tensor([[-23.3967, -23.5449],
         [-28.2544, -25.4946],
         [-48.3383, -38.6643],
         [-18.2628, -31.1393],
         [-27.5663, -16.4230],
         [-23.0929, -23.6628],
         [-27.5731, -24.7557],
         [-48.1743, -38.5547],
         [-18.5667, -31.0215],
         [-27.1888, -15.5663],
         [-22.7154, -22.8060],
         [-27.9505, -25.6124],
         [-49.0196, -39.4032],
         [-18.6403, -31.9961],
         [-27.8701, -16.3052]], grad_fn=<AddmmBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 57.,  69.],
         [ 80., 102.],
         [118., 132.],
         [ 21.,  38.],
         [104., 118.],
         [ 57.,  69.],
         [ 82., 100.],
         [118., 134.],
         [ 20.,  38.],
         [102., 120.]]))

In [46]:
model(torch.tensor([75.,63,44]))

tensor([-21.6972, -22.7859], grad_fn=<AddBackward0>)

In [47]:
model2 = nn.Sequential(
    nn.Linear(3,4),
    nn.Sigmoid(),
    nn.Linear(4,2)
)

In [51]:
opt = torch.optim.SGD(model2.parameters(),lr = 1e-3)

In [53]:
fit(1000,model2,loss_fn,opt,train_dl)

Epoch [10/1000] : Loss = 735.4065551757812]
Epoch [20/1000] : Loss = 750.51171875]
Epoch [30/1000] : Loss = 1099.036376953125]
Epoch [40/1000] : Loss = 1429.8541259765625]
Epoch [50/1000] : Loss = 1428.6256103515625]
Epoch [60/1000] : Loss = 1565.3822021484375]
Epoch [70/1000] : Loss = 1695.140869140625]
Epoch [80/1000] : Loss = 1269.5687255859375]
Epoch [90/1000] : Loss = 1440.973388671875]
Epoch [100/1000] : Loss = 1305.990966796875]
Epoch [110/1000] : Loss = 825.0865478515625]
Epoch [120/1000] : Loss = 1695.9927978515625]
Epoch [130/1000] : Loss = 1556.2393798828125]
Epoch [140/1000] : Loss = 849.6155395507812]
Epoch [150/1000] : Loss = 1757.8187255859375]
Epoch [160/1000] : Loss = 1443.185791015625]
Epoch [170/1000] : Loss = 1387.801513671875]
Epoch [180/1000] : Loss = 1193.322021484375]
Epoch [190/1000] : Loss = 1075.5914306640625]
Epoch [200/1000] : Loss = 1444.272216796875]
Epoch [210/1000] : Loss = 937.8517456054688]
Epoch [220/1000] : Loss = 1114.296142578125]
Epoch [230/1000]